services:
  nest-app:
    build:
      context: .
    ports:
      - '8080:4000'
    env_file:
      - .env
    command: ['sh', '-c', 'npx prisma db push && yarn start:prod']
    environment:
      - DATABASE_URL=postgres://postgres:3322@postgres:5432/woork_room
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.5
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3322
      - POSTGRES_DB=woork_room
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d woork_room']
      timeout: 3s
      interval: 5s
      retries: 3
  redis:
    image: redis:7
    ports:
      - '6380:6379'
